name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запускать при пуше в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Скачиваем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2

      # Устанавливаем Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Логинимся в Docker Hub (нужно указать секреты репозитория)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Сборка Docker образа
      - name: Build Docker Image
        run: docker build -t orlovanya/my-node-app:latest .

      # Пушим образ в Docker Hub
      - name: Push Docker Image
        run: docker push orlovanya/my-node-app:latest

      # Разворачиваем приложение на сервере
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
    mkdir -p ~/.ssh
    printf "%s" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh -o StrictHostKeyChecking=no -T root@185.251.90.13 << 'EOF'
      docker pull orlovanya/my-node-app:latest
      docker stop app || true
      docker rm app || true
      docker run -d -p 3000:3000 --name app orlovanya/my-node-app:latest
    EOF
